### ISSUE TITLE
GetAcademicExperienceByVolunteer, GetAcademicExperienceByVolunteer, SaveAcademicExperience no funciona

### ISSUE THREAD

**Issue by josperrod9** [ISPP-P2/HeartForChangeBackend#61]
Cuando intentamos cargar los datos de Experiencia académica para un voluntario o un beneficiario aparece el siguiente fallo **_The beneficiary with this ID doesn't exist!_** y para guardarlo _**The volunteer or beneficiary doesn't exist**_.
IMPORTANTE: Comprobar también para experiencia laboral

**Comment by migrivros** [comment]
Now it's working correctly!
